version: "3"

services:
  app:
    build: ./task-app/
    container_name: "python_app" 
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - "6379:6379"
volumes:
  redis_data: {}  
